import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {fileURLToPath} from 'node:url';
import {_electron} from 'playwright';
import {builderFixture,installBuilderFixture} from './fixtures/builder-flow.mjs';

const fixture=fileURLToPath(new URL('fixtures/window-smoke.mjs',import.meta.url));
const userData=await mkdtemp(join(tmpdir(),'asphodel-builder-smoke-'));
const flags=process.platform==='linux'&&process.getuid?.()===0?['--no-sandbox']:[];
let electron;
try {
  electron=await _electron.launch({args:[...flags,fixture],env:{...process.env,ASPHODEL_TEST_USER_DATA:userData},timeout:20_000});
  const page=await electron.firstWindow();page.setDefaultTimeout(10_000);const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.waitForFunction(()=>window.asphodelDesktop&&document.querySelector('#backend-status')?.textContent==='Prêt');
  await electron.evaluate(({BrowserWindow})=>{const w=BrowserWindow.getAllWindows()[0];w.setFullScreen(false);w.setContentSize(1366,768);});
  await page.waitForFunction(()=>innerWidth===1366&&innerHeight===768);
  const data=await builderFixture();await page.evaluate(installBuilderFixture,data);await page.locator('#nav-deck-lab').click();
  await page.locator('[data-view=builder]').click();await page.locator('[data-open-deck="saved:1"]').click();await page.locator('[data-view=table]').click();
  const table=page.locator('.lab-table');await table.locator('.dt-card').first().waitFor();await table.locator('[data-dt=fit]').click();
  if(process.env.ASPHODEL_BUILDER_SCREENSHOT)await page.screenshot({path:`${process.env.ASPHODEL_BUILDER_SCREENSHOT}-initial.png`});
  const world=table.locator('.dt-world'),camera=await world.getAttribute('style');
  await table.locator('.dt-primary-tools [data-dt=search]').click();
  assert.equal(await table.locator('[aria-controls=dt-search-panel]').getAttribute('aria-expanded'),'true');
  assert.equal(await page.evaluate(()=>{const c=document.querySelector('.dt-canvas').getBoundingClientRect(),p=document.querySelector('.dt-search').getBoundingClientRect();return c.right<=p.left+1;}),true,'desktop panel reserves space');
  if(process.env.ASPHODEL_BUILDER_SCREENSHOT)await page.screenshot({path:`${process.env.ASPHODEL_BUILDER_SCREENSHOT}-search.png`});
  await page.keyboard.press('Escape');assert.equal(await table.locator('.dt-search').isVisible(),false);
  assert.equal(await world.getAttribute('style'),camera,'panels preserve the camera');
  await table.locator('.dt-primary-tools [data-dt=analysis]').click();await table.locator('.dt-analysis').waitFor();
  if(process.env.ASPHODEL_BUILDER_SCREENSHOT)await page.screenshot({path:`${process.env.ASPHODEL_BUILDER_SCREENSHOT}-analysis.png`});
  await page.keyboard.press('Escape');
  assert.equal(await table.locator('.dt-heading').evaluate(el=>el.getBoundingClientRect().height),48,'compact header');
  await page.emulateMedia({reducedMotion:'reduce'});
  await table.locator('.dt-primary-tools [data-dt=analysis]').click();
  assert.equal(await table.locator('.dt-analysis').evaluate(el=>el.getAnimations().length),0,'reduced motion skips panel entrance');
  await page.keyboard.press('Escape');
  await page.emulateMedia({reducedMotion:'no-preference'});
  const restingCanvas=await table.locator('.dt-canvas').boundingBox();
  await table.locator('.dt-card').first().click();
  assert.deepEqual(await table.locator('.dt-canvas').boundingBox(),restingCanvas,'selection does not resize or shift the table');
  assert.equal(await page.evaluate(()=>{const c=document.querySelector('.dt-canvas').getBoundingClientRect(),s=document.querySelector('.dt-selection').getBoundingClientRect();return s.top>=c.bottom-1&&s.bottom<=innerHeight;}),true,'selection stays outside the canvas');
  const first=table.locator('.dt-card').first(),beforeDrag=await first.getAttribute('style'),box=await first.boundingBox();
  await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+24,box.y+box.height/2+12,{steps:4});await page.mouse.up();
  assert.notEqual(await first.getAttribute('style'),beforeDrag,'card drag survives the reserved selection row');
  const included=()=>page.evaluate(()=>window.builderSmoke.project.groups.filter(g=>!g.maybeboard).reduce((n,g)=>n+g.entries.reduce((n,e)=>n+e.quantity,0),0));
  await table.locator('[data-dt=exclude]').click();await page.waitForFunction(()=>window.builderSmoke.project.groups.filter(g=>!g.maybeboard).flatMap(g=>g.entries).length===8);
  assert.equal(await included(),8);
  await table.locator('[data-history=undo]').click();await page.waitForFunction(()=>window.builderSmoke.project.groups.filter(g=>!g.maybeboard).flatMap(g=>g.entries).length===9);
  await table.locator('.dt-card').first().click();
  const target=table.locator('.dt-card').nth(1);await target.click({modifiers:['Shift']});
  await table.locator('.dt-new-pile summary').click();await table.locator('#dt-pile-name').fill('Plan de jeu');await table.locator('.dt-pile-form button').click();
  await table.locator('.dt-pile').waitFor();
  await table.locator('.dt-canvas').focus();await page.keyboard.press('Escape');await table.locator('[data-dt=note]').click();
  const note=table.locator('[data-note-text]').first();await note.fill('Protéger Kodama');await note.blur();
  await page.waitForFunction(()=>window.builderSmoke.project.workspace.notes?.[0]?.text==='Protéger Kodama');
  await table.locator('.dt-primary-tools [data-dt=search]').click();await table.locator('.dt-search-form input:not([type=checkbox])').fill(data.candidate.name);await table.locator('.dt-search-form button').click();
  await table.locator('.dt-search-results button').first().click();await page.waitForFunction(name=>window.builderSmoke.project.groups.some(g=>g.maybeboard&&g.entries.some(e=>e.card.name===name)),data.candidate.name);
  await table.locator('.dt-search [data-dt=search]').click();
  const saved=await page.evaluate(()=>window.builderSmoke.project);
  assert.ok(saved.groups.some(g=>g.maybeboard&&g.entries.some(e=>e.card.name===data.candidate.name)),'search adds a candidate');assert.equal(await included(),9,'candidate does not alter deck membership');
  if(process.env.ASPHODEL_BUILDER_SCREENSHOT)await page.screenshot({path:`${process.env.ASPHODEL_BUILDER_SCREENSHOT}-desktop.png`});
  for(const [width,height] of [[900,700],[390,844]]) {
    await electron.evaluate(({BrowserWindow},size)=>BrowserWindow.getAllWindows()[0].setContentSize(...size),[width,height]);
    await page.waitForFunction(size=>innerWidth===size[0]&&innerHeight===size[1],[width,height]);
    assert.equal(await page.evaluate(()=>{const root=document.querySelector('.lab-table'),work=document.querySelector('.dt-workbar'),tools=document.querySelector('.dt-primary-tools');return root.scrollWidth<=innerWidth+1&&work.scrollWidth<=work.clientWidth+1&&tools.getBoundingClientRect().right<=innerWidth;}),true,`tools fit ${width}px`);
    await table.locator('.dt-card').first().evaluate(el=>el.click());
    assert.equal(await table.locator('.dt-selection').evaluate(el=>{const box=el.getBoundingClientRect();return [...el.querySelectorAll('button,input,select,summary')].filter(e=>e.getClientRects().length).every(e=>e.getBoundingClientRect().bottom<=box.bottom+1);}),true,`selection controls stay in their row at ${width}px`);
    await table.locator('[data-dt=clear]').click();
    if(process.env.ASPHODEL_BUILDER_SCREENSHOT)await page.screenshot({path:`${process.env.ASPHODEL_BUILDER_SCREENSHOT}-${width}.png`});
  }
  await table.locator('.dt-canvas').focus();await page.keyboard.press('Escape');
  await electron.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setContentSize(1366,768));
  await page.waitForFunction(()=>innerWidth===1366&&innerHeight===768);
  const beforePan=await world.getAttribute('style'),canvas=await table.locator('.dt-canvas').boundingBox();
  await table.locator('[data-dt=pan]').click();await page.mouse.move(canvas.x+100,canvas.y+20);await page.mouse.down();await page.mouse.move(canvas.x+140,canvas.y+40,{steps:4});await page.mouse.up();await table.locator('[data-dt=pan]').click();
  assert.notEqual(await world.getAttribute('style'),beforePan,'visible pan tool moves the camera');
  await table.locator('.dt-create summary').click();await table.locator('#dt-zone-name').fill('Protection');await table.locator('.dt-zone-form button').click();
  await table.locator('.dt-zone input[value=Protection]').waitFor();
  await page.waitForFunction(()=>window.builderSmoke.project.workspace.zones.some(z=>z.name==='Protection'));
  const snapshot=await page.evaluate(()=>window.builderSmoke.project);
  await page.reload();await page.waitForFunction(()=>window.asphodelDesktop&&document.querySelector('#backend-status')?.textContent==='Prêt');
  await page.evaluate(installBuilderFixture,{...data,project:snapshot});await page.locator('#nav-deck-lab').click();await page.locator('[data-view=builder]').click();await page.locator('[data-open-deck="saved:1"]').click();await page.locator('[data-view=table]').click();
  await page.locator('.dt-pile').waitFor();assert.equal(await page.locator('[data-note-text]').first().inputValue(),'Protéger Kodama');
  assert.equal(await page.locator('.dt-world').evaluate((el,camera)=>{const reference=document.createElement('div');reference.style.transform=`translate(${camera.x}px,${camera.y}px) scale(${camera.zoom})`;return el.style.transform===reference.style.transform;},snapshot.workspace.camera),true,'reload restores the camera transform');
  assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('asphodel.builder-draft.v1.builder-smoke')||'null')?.project?.workspace.camera??window.builderSmoke.project.workspace.camera),snapshot.workspace.camera,'reload keeps the saved camera');
  assert.deepEqual(errors,[]);console.log('Builder window smoke passed: panels/Escape/camera, reserved selection row, drag/pan, membership/undo, piles, notes, zones, candidate search, reload and 1366/900/390px layouts.');
}finally{if(electron)await electron.close();await rm(userData,{recursive:true,force:true});}
