import type { Sheet } from './deck-model';
import { analyzeCommander, COMMANDER_RULES_DATE, type CommanderIssue } from './commander-analysis';
import type { CommanderLookupState } from './commander-catalog';
import { escapeTagText as esc } from './deck-tags';
const labels = { ok: 'Vérifié', error: 'À corriger', unknown: 'À vérifier' };
function issueHtml(issue: CommanderIssue): string {
  const buttons = (names: string[]) => names.map(name => `<button type="button" data-commander-inspect="${esc(name)}">${esc(name)}</button>`).join('');
  return `<li data-commander-issue="${issue.status}"><strong>${labels[issue.status]}</strong> · ${esc(issue.message)}${issue.cards.length ? `<div class="lab-commander-cards">${buttons(issue.cards.slice(0, 4))}</div>${issue.cards.length > 4 ? `<details><summary>${issue.cards.length - 4} autres cartes</summary><div class="lab-commander-cards">${buttons(issue.cards.slice(4))}</div></details>` : ''}` : ''}</li>`;
}
export function commanderSummary(sheet: Sheet, lookup: CommanderLookupState): string {
  const report = analyzeCommander(sheet, lookup.facts);
  const status = report.errors ? 'error' : report.unknown ? 'unknown' : 'ok';
  return `<section class="lab-commander-analysis" aria-label="Vérifications Commander"><header><h4>Vérifications Commander</h4><span class="lab-commander-status" data-commander-status="${status}" role="status">${report.errors ? `${report.errors} problème${report.errors > 1 ? 's' : ''}` : report.unknown ? 'Vérification partielle' : 'Aucun problème détecté'}${report.unknown ? ` · ${report.unknown} point${report.unknown > 1 ? 's' : ''} à vérifier` : ''}</span></header><p>Commander multijoueur · candidats et cartes écartées exclus. Diagnostic consultatif : tu peux continuer à construire.</p><div class="lab-commander-checks">${report.checks.map(c => `<details data-commander-check="${c.id}" ${c.status !== 'ok' ? 'open' : ''}><summary><span>${esc(c.label)}</span><strong data-check-status="${c.status}">${labels[c.status]}</strong></summary><p>${esc(c.summary)}</p>${c.issues.length ? `<ul>${c.issues.slice(0, 12).map(issueHtml).join('')}</ul>${c.issues.length > 12 ? `<details><summary>${c.issues.length - 12} autres points</summary><ul>${c.issues.slice(12).map(issueHtml).join('')}</ul></details>` : ''}` : ''}</details>`).join('')}</div><button type="button" data-action="verify-commander" ${lookup.busy || !report.total ? 'disabled' : ''}>${lookup.busy ? `Vérification locale · ${lookup.done} / ${lookup.total}` : 'Vérifier avec le catalogue local'}</button><p class="lab-commander-source">${lookup.checkedAt ? `Dernière vérification locale : ${esc(new Date(lookup.checkedAt).toLocaleString('fr-FR'))}. Date du fichier de catalogue : ${esc(lookup.snapshotDate ? new Date(lookup.snapshotDate).toLocaleDateString('fr-FR') : 'indisponible')}.` : 'Analyse des données enregistrées. Le bouton relit le catalogue installé sans télécharger de cartes ni changer les illustrations.'}${lookup.missing.length ? ` ${lookup.missing.length} carte${lookup.missing.length > 1 ? 's' : ''} absente${lookup.missing.length > 1 ? 's' : ''} du catalogue ; leurs données enregistrées restent utilisées.` : ''}</p>${lookup.error ? `<p class="lab-commander-error" role="alert">${esc(lookup.error)} Les derniers résultats complets restent disponibles.</p>` : ''}<details class="lab-commander-scope"><summary>Portée de la vérification</summary><p>Règles de construction au ${COMMANDER_RULES_DATE}. Partenariats classiques, nommés, variantes reconnues, backgrounds et Doctor’s companion. Les choix de couleur avant la partie et les textes non reconnus restent à vérifier. Les noms interchangeables ne sont regroupés que lorsque le catalogue partage leur identité Oracle ; les alias rares nécessitent une revue. Companions et règles de groupe ne sont pas vérifiés. Les statuts d’interdiction reflètent tes données locales, pas une liste en direct.</p></details></section>`;
}
